### ISSUE TITLE
Avoid creating references with property.toValue()

### ISSUE THREAD

**Issue by appsforartists** [pozadi/kefir#69] opened 2015-03-11 02:46 UTC
I'm exploring the use of Kefir to create an isomorphic Flux implementation.  My Kefir property will be used on a JS server, serialized to JSON, then deserialized back into a Kefir property on the client.

I see that Kefir implements `onValue` and `offValue`.  The presence of both methods leads me to believe there's room for a memory leak if someone calls `onValue` without calling `offValue`.  Is this correct?

It'd be nice to have the ability to pull the last value from a property without adding a listener - something like this:

    var serializedState = JSON.stringify(myProperty.toValue());

I'd get a single sync lookup of the property's last value and could forget about the property after that on the server.

**Comment by pozadi** [comment] 2015-03-11 08:39
Hi, this was discussed here https://github.com/pozadi/kefir/issues/50 . Seems like it kind of possible to implement, but it will lead user to wrong expectations, and basically `.toValue()` will be almost useless.

Here is example of I mean:

```js
var emitter = Kefir.emitter();
var property = emitter.toProperty();
emitter.emit(1); // property won't get this value because it not active at the moment
property.toValue(); // -> udefined
```
See https://pozadi.github.io/kefir/#active-state to learn what "not active" means.

Fix:
```js
var emitter = Kefir.emitter();
var property = emitter.toProperty();
property.onValue(function() {}); // activating the property
emitter.emit(1);
property.toValue(); // -> 1
```
But now you again have to add a subscriber to the property, and care to remove it later.

So unfortunately you have to use subscriber to make things work, but consider using [takeUntilBy](https://pozadi.github.io/kefir/#take-until-by) instead of unsubscribing to free resources.

```js
var observable = Kefir.emitter();
var disposer = Kefir.emitter();
observable.takeUntilBy(disposer).onValue(fn);

// this will make everybody to unsubscribe from each other,
// including `observable` from `disposer`
disposer.emit(1); 

observable = null;
disposer = null;
// now everything can be garbage collected
```

Closing as duplicate of #50

**Closed by pozadi** 2015-03-11 08:39 UTC
